"""add_direct_orders_table

Revision ID: 96986b6e1b05
Revises: 6181b2bacee8
Create Date: 2026-02-24 20:31:45.304410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96986b6e1b05'
down_revision: Union[str, None] = '6181b2bacee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_orders',
    sa.Column('contractor_company_id', sa.Uuid(), nullable=False),
    sa.Column('subcontractor_company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('specialty_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_orders')
    # ### end Alembic commands ###
